# Generated by Django 4.1.7 on 2023-04-07 15:05

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAPEJsonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', djongo.models.fields.JSONField()),
            ],
        ),
        migrations.RenameModel(
            old_name='JsonModel',
            new_name='BIDASKJsonModel',
        ),
    ]
